name: Deploy to Firebase

on:
  push:
    branches:
      - main # Reemplaza 'main' con el nombre de la rama que deseas utilizar

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build # Reemplaza 'npm run build' con el comando nec
